#!/bin/bash 
if [ $# -eq 0 ] || [ $1 = "-h" ] || [ $1 = "--help" ] ; then
    echo -e "usage: ns new_script.bash\n\tcreates a new script and starts editing it"
    exit
fi
script=$1
touch $script
if [ ${script: -3} == ".py" ] ;then
    echo -e '#!/usr/bin/python3\n' > $script
else
    echo -e '#!/bin/bash\n' > $script
fi
emacs $script && chmod +x $script
