#!/bin/bash
# find unknown things on the network, I use this a lot to find small devices with an IP address that are in development on the network
scan-local | grep "(Unknown)" -B 2 | grep "scan report for 10.20." -A 2
